node:
  ip: 0.0.0.0
  port: 9527
  key_path: /app/keys/priv.bin
  use_static_keys: true
  workspace_root: /tmp/node
  runtime_path: /app/runtime 
  boot_nodes: {{ range (ds "boot_nodes") }} 
     {{ range (.) }}- {{.}}{{ end }}{{ end }}
rest:
  ip: 0.0.0.0
  port: 8081
protocol:
  role: {{ .Env.NODE_ROLE }}
logging:
  file_path: stdout
  level: info
repository:
  url: http://localhost:8080/
chain:
  address_key: "alice"
  rpc: {{ .Env.CHAIN_RPC_NODE }}
