node:
  name: head#1
  ip: 0.0.0.0
  port: 9527
  boot_nodes:
  use_static_keys: true
rest:
  ip: 0.0.0.0
  port: 8081
protocol:
  role: head
logging:
  file_path: stdout
  level: info
repository:
  url: http://localhost:8080/repo.json
chain:
  address_key: "alice"
  rpc: "http://0.0.0.0:26657"
