node:
  name: worker#1
  ip: 0.0.0.0
  port: 0
  boot_nodes:
  use_static_keys: true
  workspace_root: /tmp/worker
  runtime_path: /tmp/runtime
rest:
  ip: 0.0.0.0
  port: 8081
protocol:
  role: worker
logging:
  file_path: stdout
  level: info
repository:
  url: http://localhost:8080/
chain:
  address_key: "alice"
  rpc: "http://0.0.0.0:26657"
