node:
  name: worker#1
  ip: 0.0.0.0
  # 0 means random port
  port: 0
  # join the blockless network by boot strapping to one of our worker nodes
  boot_nodes:
    - /ip4/147.75.84.103/tcp/32536/p2p/12D3KooWDCELEqCuHGqqRiMwSjPFLAKnVjL6mGVpSHASmmxTqovc
  workspace_root: /tmp/worker
  runtime_path: /tmp/runtime
rest:
  ip: 0.0.0.0
  port: 8081
protocol:
  role: worker
logging:
  file_path: stdout
  level: info
repository:
  url: http://localhost:8080/
chain:
  address_key: "alice"
  rpc: "http://0.0.0.0:26657"
