name: build docker images

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "docker tag"
        required: true
        default: "latest"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "1.18"
          check-latest: true
      - uses: actions/checkout@v2
      - name: build
        run: |
          GOOS=linux GOARCH=amd64 make
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USER }}" --password-stdin
          docker build . --tag ghcr.io/${{ github.repository }}:${{ github.event.inputs.tag }}-head -f HeadNode.Dockerfile 
          docker build . --tag ghcr.io/${{ github.repository }}:${{ github.event.inputs.tag }}-worker -f WorkerNode.Dockerfile 
          docker push ghcr.io/${{ github.repository }}:${{ github.event.inputs.tag }}
